eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

microservice:
  payment-service:
    endpoints:
      fetchPaymentById:
        uri: http://PAYMENT-SERVICE/payment/
  user-service:
    endpoints:
      fetchUserById:
        uri: http://USER-SERVICE/users/

logging:
  file:
    name: F:/logs/centralized_log.logs
